name: Notify Teams on PR Merge

on:
  pull_request:
    branches: ["main"]
    types:
      - closed

jobs:
  notify-teams:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Microsoft Teams
        run: |
          PAYLOAD=$(jq -n \
          --arg text "**Pull Request Merged**\n\nPR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }} has been merged into \`main\` by **${{ github.actor }}**.\n\n[View PR](${{ github.event.pull_request.html_url }})" \
          '{ text: $text }')

          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ secrets.TEAMS_WEBHOOK_URL }}

